# frozen_string_literal: true

module Decidim
  module RestApi
    # This controller is the abstract class from which all other controllers of
    # this engine inherit.
    #
    # Note that it inherits from `Decidim::Components::BaseController`, which
    # override its layout and provide all kinds of useful methods.
    class ApplicationController < Decidim::ApplicationController

      before_action :api_authenticate

      private

      # Validates token from X-Api-Key header
      # Token could be generated by SecureRandom.uuid
      # Authentication is skipped in development env
      def api_authenticate
        return if Rails.env.development?
        return if params[:noauth]

        authenticate_api_key || render_unauthorized
      end

      def authenticate_api_key
        api_key = request.headers['X-Api-Key']
        api_key == ENV.fetch('REST_API_TOKEN')
      end

      def render_unauthorized
        render json: 'Bad credentials', status: 401
      end

    end
  end
end
