# frozen_string_literal: true
module Decidim
  module Repository
    # FIX wrong redirection from https to http for blobs, generated by main_app.url_for(blob)
    # Redirects to rails service for downloading attachments
    class BlobsController < ActionController::Base
      include ActiveStorage::SetBlob

      before_action do
        ActiveStorage::Current.host = Rails.env.development? ? request.base_url : "https://#{request.host_with_port}"
      end

      def show
        expires_in ActiveStorage.service_urls_expire_in
        redirect_to  Rails.application.routes.url_helpers.rails_blob_url(
          @blob, disposition: params[:disposition] || "inline",
          host: Rails.env.development? ? request.base_url : "https://#{request.host_with_port}"
        )
      end
    end
  end
end
